/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenin
 */
public class EstudianteFrame extends javax.swing.JFrame {
    private DefaultTableModel modeloTablaHistorial;
    private String usuarioEstudiante;

    public EstudianteFrame(String usuario) {
        initComponents();
        this.usuarioEstudiante = usuario;
        this.setTitle("Módulo Estudiante - Historial SGA-R");
        lblBienvenido.setText("Bienvenido(a), Alumno " + usuario + ".");
        this.setLocationRelativeTo(null); 
        
        inicializarTablaHistorial();
        cargarDatosHistorial();
    }
    
    private void inicializarTablaHistorial() {
        modeloTablaHistorial = new DefaultTableModel(
            new Object[]{"Fecha", "Curso", "Docente", "Estado"}, 0 
        ) {
   
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tblHistorial.setModel(modeloTablaHistorial);
    }
    
    private void cargarDatosHistorial() {
        modeloTablaHistorial.addRow(new Object[]{"2025-10-15", "Programación I", "Docente A", "PRESENTE"});
        modeloTablaHistorial.addRow(new Object[]{"2025-10-16", "Matemáticas", "Docente B", "AUSENTE"});
        modeloTablaHistorial.addRow(new Object[]{"2025-10-17", "Programación I", "Docente A", "PRESENTE"});
        modeloTablaHistorial.addRow(new Object[]{"2025-10-18", "Matemáticas", "Docente B", "PRESENTE"});
        modeloTablaHistorial.addRow(new Object[]{"2025-10-19", "Programación I", "Docente A", "AUSENTE"});
        

        calcularAvance();
    }

    private void calcularAvance() {
        int totalSesiones = modeloTablaHistorial.getRowCount();
        int faltas = 0;
        
        for (int i = 0; i < totalSesiones; i++) {
 
            if (modeloTablaHistorial.getValueAt(i, 3).equals("AUSENTE")) {
                faltas++;
            }
        }
        
        int asistencias = totalSesiones - faltas;
        double porcentajeAsistencia = (totalSesiones > 0) ? ((double) asistencias / totalSesiones) * 100 : 0;
        
   
        lblFaltas.setText("Total de Faltas: " + faltas);
        lblPorcentaje.setText(String.format("Asistencia Total Acumulada: %.2f%%", porcentajeAsistencia));
    }
    public EstudianteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenido = new javax.swing.JLabel();
        lblPorcentaje = new javax.swing.JLabel();
        lblFaltas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        lblTituloHistorial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBienvenido.setText("Bienvenido");

        lblPorcentaje.setText("Porcentaje:");

        lblFaltas.setText("Faltas:");

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHistorial);

        lblTituloHistorial.setText("Historial:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lblTituloHistorial)
                .addGap(52, 52, 52)
                .addComponent(lblFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblBienvenido)
                        .addGap(207, 207, 207))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcentaje)
                    .addComponent(lblFaltas)
                    .addComponent(lblTituloHistorial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblFaltas;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JLabel lblTituloHistorial;
    private javax.swing.JTable tblHistorial;
    // End of variables declaration//GEN-END:variables
}
